backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\forms\LoginForm;
use common\models\Documents;
use common\models\Platforms;
use common\models\Settings;
use yii\web\Controller;
use yii\filters\AccessControl;
use Yii;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'logout' => ['post'],
//                ],
//            ],
        ];
    }
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        \Yii::$app->view->registerMetaTag([
            'name' => 'description',
            'content' => 'ООО «ЯнТранс» предоставляет услуги аренды автовышки в Минске и Беларуси, а также сдает внаем телескопические погрузчики и самоходные подъемники. Аренда спецтехники в Минске: от 12 до 40 метров!'
        ]);
        return $this->render('index');
    }

    public function actionAbout()
    {
        \Yii::$app->view->registerMetaTag([
            'name' => 'description',
            'content' => 'О компании ООО "ЯнТранс" и услугах по аренде автовышек'
        ]);
        return $this->render('about');
    }

    public function actionDocuments()
    {
        \Yii::$app->view->registerMetaTag([
            'name' => 'description',
            'content' => 'Заявка на аренду автоподъемника и другой техники'
        ]);
        $doc = Documents::find()->all();
        return $this->render('documents',['documents'=> $doc]);
    }

    public function actionRentalInformation($tab)
    {
        \Yii::$app->view->registerMetaTag([
            'name' => 'description',
            'content' => 'Арендовать автовышку, телескопический погрузчик или самоходный подъемник в Минске по привлекательной цене'
        ]);
        $platform = Platforms::find()->where(['type'=>Platforms::PLATFORMS])->all();
        $loader = Platforms::find()->where(['type'=>Platforms::LOADER])->all();
        $lift = Platforms::find()->where(['type'=>Platforms::LIFT])->all();

        return $this->render('rental-information', [
            'platforms' => $platform,
            'loaders' => $loader,
            'lifts' => $lift,
	        'tab' => $tab
        ]);
    }

    public function actionRepair(){

        return $this->render('repair');
    }

    public function actionContacts(){

        \Yii::$app->view->registerMetaTag([
            'name' => 'description',
            'content' => 'Связаться с ООО «ЯнТранс».'
        ]);
        return $this->render('contacts');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        $this->layout = false;
        if (!Yii::$app->user->isGuest) {
            $this->redirect('admin/index');
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $this->redirect('admin');
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }



}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */
$mts =  \common\models\Settings::find()->where(['label'=>'Мтс'])->one()->text;
$velcom = \common\models\Settings::find()->where(['label'=>'Velcom'])->one()->text;
$life = \common\models\Settings::find()->where(['label'=>'Life'])->one()->text;
$fax = \common\models\Settings::find()->where(['label'=>'Факс'])->one()->text;
$email = \common\models\Settings::find()->where(['label'=>'Email'])->one()->text;
\frontend\assets\AboutAsset::register($this);
$this->title = 'Аренда спецтехники в Минске';
?>
<div class="container">
    <nav class="breadcrumb">
        <a class="breadcrumb-item" href="/">Главная</a>
        <span class="breadcrumb-item active">О компании</span>
    </nav>
</div>
<div class="container">
    <h3 class="pt-3">О компании</h3>
    <div class="line"></div>
    <div class="row">
        <div class="col-md-8 pr-5">
            <div class="company-text " >
                <?= \common\models\Settings::find()->where(['label'=>'О компании'])->one()->text; ?>
            </div>
        </div>
        <div class="col-md-4">
            <div class="company-info">
                <p class="text-bold">Телефоны</p>
                <p class="velcom"><a href="tel:<?= $velcom?>"><?= $velcom?></a></p>
                <p class="mts"><a href="tel:<?= $mts ?>"><?= $mts?></a></p>
                <p class="life"><a href="tel:<?= $life?>"><?= $life?></a></p>
                <p class="fax"><a href="#"><?= $fax?><span> (факс)</span></a></p>
                <p class="text-bold pt-2">E-mail</p>
                <p class="email"><a href="mailto:<?= $email?>"><?= $email?></a></p>
            </div>
        </div>
    </div>
</div>

frontend/views/site/documents.php
<?php

/* @var $this yii\web\View */

\frontend\assets\DocumentsAsset::register($this);

$this->title = 'Аренда спецтехники в Минске';
?>
<div class="container">
    <nav class="breadcrumb">
        <a class="breadcrumb-item" href="/">Главная</a>
        <span class="breadcrumb-item active">Документы</span>
    </nav>
</div>
<div class="container">
    <h3 class="pt-3">Документы</h3>
    <div class="line"></div>
    <div class="doc-text">
        <?php foreach ($documents as $document) {?>
            <p> <a href="/doc/<?= $document->file ?> "><?= $document->name ?> (<?= $document->size ?>)</a>
        <a href="/doc/<?= $document->file ?> "> <img src="/img/download.svg" alt="Заявка на аренду автоподъемника"></a></p>
        <?php } ?>
    </div>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */

\frontend\assets\IndexAsset::register($this);

$this->title = 'Аренда спецтехники в Минске';
?>
<section>
    <div class="container-fluid lease-background">
        <div class="container main-lease">
            <h3>Аренда спецтехники в Минске
                <br> и по всей территории РБ: техника от 12 до 40 метров.</h3>
            <ul class="list-unstyled">
                <li>Собственный автопарк 8 машин.</li>
                <li>Возможна работа в праздничные и выходные дни.</li>
                <li>Возможна работа более 8 часов в сутки.</li>
                <li>При заказе от 2 ед. скидки до 20 %.</li>
            </ul>
            <?= Html::a('Арендовать', ['/order'], ['class' => 'btn btn-primary']) ?>
            <img src="/img/main1.png" alt="Автовышки" class="lease-image">
        </div>
    </div>
</section>
<section>
    <div class="container select-technology mb-5">
        <h3 class="center">Выберите специальную технику</h3>
        <div class="machine mb-4">
            <div class="min-line"></div>
            <img src="/img/lever-machine.svg" alt="Автовышки">
            <div class="min-line"></div>
        </div>
        <div class="row">
            <div class="col-md-12 col-lg-auto ">
		        <?= Html::a('Аренда автовышки', ['site/rental-information/platform'], ['class' => 'btn btn-primary lease-btn']) ?>
            </div>
            <div class="col-md-12 col-lg-auto">
                <?= Html::a('Аренда телескопического<br> погрузчика', ['site/rental-information/loader'], ['class' => 'btn btn-primary']) ?>
            </div>
            <div class="col-md-12 col-lg-auto">
                <?= Html::a('Аренда самоходных<br> подъемников', ['site/rental-information/lift'], ['class' => 'btn btn-primary']) ?>
            </div>
        </div>
        <div class="row mt-1 pb-3">
            <div class="col-xl-auto col-lg-4 pt-2 mr-2">
                <img src="/img/lease-1.png" alt="Автовышки">
            </div>
            <div class="col-xl-auto col-lg-4 pt-4 big-platform  pl-0" >
                <img class="pt-1" src="/img/platform5.png" alt="Автовышки" width="300">
            </div>
            <div class="col-xl-auto col-lg-4 px-0">
                <img class="pt-2" src="/img/lease3.png" alt="Автовышки">
            </div>
        </div>

    </div>
</section>
<section>
    <div class="container-fluid main-desc-background">
        <div class="container main-desc">
            <div class="row pt-5">
                <div class="col-md-12 col-lg-8">
                    <h2 class="pb-3">О компании</h2>
                    <?= \common\models\Settings::find()->where(['label'=>'Главная - о компании'])->one()->text; ?>
                </div>
                <div class="col-md-12 col-lg-auto desc-images">
                    <div class="desc-image">
                        <img src="/img/Group16.svg" alt="Автовышки">
                        <div class="image-text units">
                            <p class="white">Скидка
                                при заказе</p>
                            <p class="silver">от <span>2</span> единиц</p>
                        </div>
                    </div>
                    <div class="desc-image">
                        <img src="/img/Group18.svg" alt="Автовышки">
                        <div class="image-text technique">
                            <p class="white">Скидка
                                при заказе
                                техники </p>
                            <p class="silver">от <span>5</span> смен</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="tangle footer">
            <img src="/img/tangle.svg" alt="Автовышки">
        </div>
    </div>
</section>

<section>
    <div class="container  main-links">
        <div class="row">
            <div class="col item">
                <img src="/img/book.svg" alt="Автовышки">
                <?= Html::a('Книга замечаний и<br> предложений', ['/complaint-book']) ?>
            </div>
            <div class="col item">
                <img src="/img/question.svg" alt="Автовышки">
                <?= Html::a('Вопрос-ответ', ['/issues']) ?>
            </div>
            <div class="col item">
                <img src="/img/tools.svg" alt="Автовышки">
                <?= Html::a('Ремонт автовышек', ['site/repair']) ?>
            </div>
        </div>
    </div>
</section>
<!--<section>-->
<!--    <div class="container discounts">-->
<!--        <img src="/img/discounts.svg" alt="Автовышки">-->
<!--    </div>-->
<!--</section>-->

<section>
    <div class="container-fluid discounts-background">
        <div class="container discounts">
            <div class="row pt-2">
                <div class="col-auto">
                    <p class="platform-title">Автовышки</p>
                    <p class="percentages-title">Скидка</p>
                </div>
                <div class="col-auto pl-0">
                    <p class="percentages">5%</p>
                </div>
                <div class="col pt-3 pl-3">
                    <p class="platform">при заказе</p>
                    <p class="blue">от 2 машин</p>
                </div>
                <div class="col pt-3">
                    <p class="platform">на срок</p>
                    <p class="blue">более 5 смен</p>
                </div>
            </div>
        </div>
    </div>
</section>

frontend/views/site/repair.php
<?php

\frontend\assets\RepairAsset::register($this);

/* @var $this yii\web\View */
$settings = \common\models\Settings::find()->one();
$phones = json_decode($settings->numbers, true);
$this->title = 'Аренда спецтехники в Минске';
?>
<div class="container">
    <nav class="breadcrumb">
        <a class="breadcrumb-item" href="/">Главная</a>
        <span class="breadcrumb-item active">Ремонт автовышки</span>
    </nav>
</div>
<div class="container-fluid key">
    <div class="container">
        <h3 class="pt-3">Ремонт автовышки: гарантированное качество работ</h3>
        <div class="line"></div>
        <div class="repairs">
            <p>В нашей компании вы можете заказать следующие услуги:</p>
            <ul>
                <li>Диагностику автоподъемников.</li>
                <li>Ремонтные работы в отношении гидрооборудования.</li>
                <li>Ремонт электрооборудования.</li>
                <li>Плановое техническое обслуживание оборудования (ТО).</li>
                <li>Шиномонтаж.</li>
            </ul>
            <p>Сделайте выгодный заказ услуги ремонта автовышки или получите <br> ответы на все ваши вопросы - по тел.
                <a class="tel-bold" href="tel:<?= $phones['life']?>"><?= $phones['life']?>.</a></p>
            <p class="repair-bold">Мы за результативный сервис для вашей техники и внимательное отношение к вам как к клиенту!</p>
        </div>
    </div>
</div>